version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - bgianfo
  ignore:
  - dependency-name: Humanizer
    versions:
    - 2.9.7
